### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [computernewb/collab-vm-server#78]
closed

**Comment by yellows111** [comment]
other than this being a &lt;guacamole problem&gt; (Seriously, can we have more relevant tags for these issues, like a &lt;not our issue&gt;, &lt;irrelevant&gt; or &lt;pre 1.2.11&gt;?) 

I never cloned 1.2.11?, I'm working on test/1.3.0 now, but I don't know why your system fails to compile with this:
```cpp
In file included from src/GuacWebSocket.cpp:5:
src/websocketmm/websocket_user.h:110:28: error: no member named 'tcp_stream' in namespace 'boost::beast'
                websocket::stream<beast::tcp_stream> ws_;
                                  ~~~~~~~^
In file included from src/GuacBroadcastSocket.cpp:6:
src/websocketmm/websocket_user.h:110:28: error: no member named 'tcp_stream' in namespace 'boost::beast'
                websocket::stream<beast::tcp_stream> ws_;
                                  ~~~~~~~^
1 error generated.
```
I do now: OP didn't install boost correctly, which meant `boost/beast/core/tcp_stream.hpp` did not exist.
After a reinstall of boost OP says it's fine, can close now?

**Comment by yellows111** [comment]
Dupes of: #37 #39 #72
Extended permission sets are expected(?) to come with a later CollabVM version, as part of the accounts system.
Plugins: Expected to come with the above at some point.
Video/Server-side logs: Seems to be unstable and very resource intensive, rather not focus on that for now.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
closed

**Comment by modeco80** [comment]
> support more than vnc. Etc, looking glass, spice…

This is a direct working point of completely removing the pile of hot garbage Guacamole is, and switching to a stream based binary protocol (where control is one stream, display is another, and CollabVM opcodes are a final one or combined with control). Internally, we're going to support:
- VNC (first and foremost)
- SPICE (as a secondary protocol)
- Agent Internal (allows the fastest screen transfers possible)

The agent internal protocol will be custom to CollabVM 1.3, however, may possibly be implementable in multiple hypervisors.

> add more roles

Finely grained permissions are going to be added alongside accounts later in development.

> plugin / add-on support.

Plugins are something we're considering, especially for VMControllers, however, we'd have to do a bit of checking to avoid old plugin ABI on new plugin ABI server or something. A bit annoying.

> custom username color selector

This is something which might be considered, especially since for the new webapp, colors won't directly be used for mod/admins (mostly for accessibility reasons). Not gonna say "yeah it's gonna be a thing", cause the webapp rewrite hasn't been even started yet.

**Comment by dakrk** [comment]
> cause the webapp rewrite hasn't been even started yet.

I've been attempting to do this for a while now but I've only got as far as somewhat functional dickamole protocol JS and not design since I absolutely _suck_ at CSS
I've been trying to get people on board with helping me out a few times but it seems not much people have the knowledge to do so and I suck at leading teams and stuff too ☹️
I Can Only Hope

**Comment by modeco80** [comment]
yeah dont worry about dealing with the POS that is guacamole its going byebye very very soon (it's not worth trying to update it - cosmic doesn't even use half of the code in src/guacamole and it seems all the server does use has been really messed with.. sucks but meh)

**Comment by dakrk** [comment]
yeah fair enough, focus should be on design and stuff then i guess up until the new protocol is ready

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
closed

**Comment by modeco80** [comment]
> GPU pass through issue might be fixed using qemu demonization, scripts, instead running directly with collab-vm-server. [still studying, unverified]

this is a BAD idea. There is a reason cvm server supervises its qemu processes.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
closed
